server:
  port: 8080
  servlet:
    context-path: /cms

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cms_shoe"
    username: root
    password: sasasa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "9O9/2AcYeimx5tbT3t9m7CLlvsGYezcFoRmlb2IgzwRCKaKXobg34jsFcOUbWOWy"